name: Build Docker and Optional Push - KM Generic

on:
  push:
    branches:
      - main
      - dev
      - demo
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
    branches:
      - main
      - dev
      - demo
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Azure Container Registry
        if: ${{ (github.event_name == 'push' && (github.ref_name == 'main' || github.ref_name == 'dev' || github.ref_name == 'demo')) || (github.event_name == 'workflow_dispatch' && (github.ref_name == 'dependabotchanges'||github.ref_name == 'main' || github.ref_name == 'dev' || github.ref_name == 'demo')) }}
        uses: azure/docker-login@v2 
        with:
          login-server: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - name: Output ACR Login Server
        run: |
          echo "ACR Login Server: ${{ secrets.ACR_LOGIN_SERVER }}"

      - name: Determine Tag Name Based on Branch
        id: determine_tag
        run: |
         if [[ "${{ github.ref_name }}" == "main" ]]; then
          echo "tagname=latest_fdp" >> $GITHUB_OUTPUT
         elif [[ "${{ github.ref_name }}" == "dev" ]]; then
          echo "tagname=dev" >> $GITHUB_OUTPUT
         elif [[ "${{ github.ref_name }}" == "demo" ]]; then
          echo "tagname=demo" >> $GITHUB_OUTPUT
         elif [[ "${{ github.ref_name }}" == "dependabotchanges" ]]; then
          echo "tagname=dependabotchanges" >> $GITHUB_OUTPUT
         else
          echo "tagname=default" >> $GITHUB_OUTPUT
       
         fi
      - name: Build and Push Docker Image for WebApp
        uses: docker/build-push-action@v6
        with:
          context: ./src/App
          file: ./src/App/WebApp.Dockerfile
          push: ${{ github.ref_name == 'main' || github.ref_name == 'dev' || github.ref_name == 'demo'  || github.ref_name == 'dependabotchanges'  }}
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER || 'acrlogin.azurecr.io' }}/dakm-app:${{ steps.determine_tag.outputs.tagname }}
            ${{ secrets.ACR_LOGIN_SERVER || 'acrlogin.azurecr.io' }}/dakm-app:${{ steps.determine_tag.outputs.tagname }}_${{ steps.date.outputs.date }}_${{ github.run_number }}

      - name: Build and Push Docker Image for api
        uses: docker/build-push-action@v6
        with:
          context: ./src/api
          file: ./src/api/ApiApp.Dockerfile
          push: ${{ github.ref_name == 'main' || github.ref_name == 'dev' || github.ref_name == 'demo'  || github.ref_name == 'dependabotchanges' }}
          tags: |
            ${{ secrets.ACR_LOGIN_SERVER || 'acrlogin.azurecr.io' }}/dakm-api:${{ steps.determine_tag.outputs.tagname }}
            ${{ secrets.ACR_LOGIN_SERVER || 'acrlogin.azurecr.io' }}/dakm-api:${{ steps.determine_tag.outputs.tagname }}_${{ steps.date.outputs.date }}_${{ github.run_number }}
